### ISSUE TITLE
401 Unathorized with spring-boot:run from scratch

### ISSUE THREAD

**Issue by alonsoir** [geeksusma/jwt-rest-controller#1]
Hi buddy, i just tried with both curl and postman, both of them with 401.

` ~/s/jwt-rest-controller> 
curl --header "Content-Type :application/json" --request POST --data '{"username" : "test@geeksusma.es", "password": "password"}' http://localhost:8080/login
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>⏎   `

`~/s/jwt-rest-controller> 
curl -H "Content-Type :application/json" -X POST -d "{"username" : "test@geeksusma.es", "password": "password"}" http://localhost:8080/login
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>⏎  `

![Captura de pantalla 2019-04-07 a las 22 16 06](https://user-images.githubusercontent.com/2405946/55689274-d3782e00-5982-11e9-8f95-96d0993919cf.png)

**Comment by geeksusma** [comment]
Extracted from the docu (see the README)

> localhost:8080/login with the next JSON: { "username" : "test@geeksusma.es", "password": "password" }

Please do a POST with the suggested JSON object.

Cheers
